---
title: "`r paste0('Special Projects for the ', maxyr, ifelse(srvy == '', '', ' '), srvy, ' Bottom Trawl Survey', ifelse(srvy == '', 's', ''))`"
date: "`r paste0('DRAFT: ', format(Sys.time(), '%B %d, %Y'))`"
output:
  officedown::rdocx_document: 
    reference_docx: styles_reference.docx   
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-no-ampersand.csl"
bibliography: "https://raw.githubusercontent.com/afsc-gap-products/citations/main/cite/bibliography.bib"
link-citations: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = "Table", 
  tab.cap.sep = ". --", 
  tab.cap.align = "left",
  fig.cap.style = "Image Caption",
  fig.cap.pre = "Figure ", 
  fig.cap.sep = ". -- ", 
  fig.align = 'left')
```

```{r summary1, child = here::here("code/template_summary_nodesc.Rmd"), results='asis'}
```

<!---BLOCK_LANDSCAPE_START--->

```{r summary2, child = here::here("code/template_summary_desc.Rmd"), results='asis'}
```

<!---BLOCK_LANDSCAPE_STOP--->

```{r projects, echo=FALSE, results='asis'}
src <- c()
for (jj in 1:nrow(dat0)) {
 # dat <- dat0[jj,]
 src[[jj]] <- knitr::knit_expand(here::here("code/template.Rmd"))
}
res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```

